<div style="width: 100%; clear: both;">
<div style="float: left; width: 50%;">
<img src="https://www.orbidi.com/wp-content/uploads/2022/12/trasp_logobaseline.png", align="left">
    <img src="https://www.orbidi.com/wp-content/uploads/2023/03/Orbidi-inicio-pymes-competitivas-e1677714972273.png", align="left">
</div>
</div>
<div style="float: right; width: 50%;">
    
<p style="margin: 0; text-align:right; padding-button: 100px;">https://www.orbidi.com/</p>
</div>
</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>

# PRUEBA TÉCNICA ORBIDI 

## AUTOR: ADRIAN FELIPE PINZON HURTADO

In [79]:
#!pip install psycopg2
#PG4Admin
import psycopg2
import requests
from pyclickup import ClickUp
import time
import json
import pandas as pd
import numpy as np
import sys

In [55]:
def extract_keys(js, field, encode=False):
    try:
        d = json.loads(js)
    except:
        d = {}
    if not encode:
        return d.get(field, None)
    else:
        return json.dumps(d.get(field, ""))
    
def extract_data_dicts( js, first, secund ):
    try:
        d = json.loads(js)
    except:
        d = {}
    #d = json.loads(js)
    try:
        e = d.get(first, {}).get(secund)
    except:
        e = {}
    return e


<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
     <strong>EXTRACT:</strong><br>

<br>
<strong>Respuesta:</strong><br> 
   
</div>

In [56]:
#Information to deliver
#Taken from https://www.jeevangupta.com/python-code-to-get-clickup-space-workspace-and-task-details-using-clickup-api/
    
def get_tasks_details(clickup_api, list_id):
    try:
        url = "https://api.clickup.com/api/v2/list/%s/task?archived=false"%list_id
        #url = "https://api.clickup.com/api/v2/list/{list_id}/task"

        headers = {"Authorization": clickup_api}
        r = requests.get(url = url, headers = headers)
        response_dict = json.loads(r.text)
        #print(response_dict)
 
        tasks = response_dict["tasks"]
 
        clickup_tasks = pd.DataFrame()
        task_list = []
        for task in tasks:
            tmp_dict = {}
            task_id = task['id']
            task_name = task['name']
            task_content = task['text_content']
            #link_id = task['link_id']
 
            tmp_dict["task_name"] = task_name
            tmp_dict["task_id"] = task_id
            tmp_dict["task_content"] = task_content
            #tmp_dict["link_id"] = task['link_id']
            tmp_dict["date_created"] = task['date_created']
            tmp_dict["status"] = task['status']['status']
            tmp_dict["creator"] = task['creator']
            tmp_dict["assignees"] = task['assignees']
            tmp_dict["watchers"] = task['watchers']
 
            #print("\n task name : %s | task id : %s "% (task_name, task_id))
 
            task_list.append(tmp_dict)
 
        clickup_tasks = pd.DataFrame.from_records(task_list)
 
        return clickup_tasks
 
    except:
        print("\n get_tasks_details Failed : ",sys.exc_info())
 

if __name__ == '__main__':
    try:
        print(" ClickUp task list and details process starts")
 
        clickup_api = "pk_3041236_DXOBGO4W2M220TSFKLKVFUDZ50WP4VG9"
        list_id = "900100953154"
 
        Data_CLIENTES = get_tasks_details(clickup_api, list_id)
        #print(Data_CLIENTES)
 
 
        print("\n ClickUp task list and details process Finished.")
    except:
        print("\n ClickUp task list and details process Failed : ", sys.exc_info())

 ClickUp task list and details process starts

 ClickUp task list and details process Finished.

In [57]:
#Data_CLIENTES = get_tasks_details("pk_3041236_DXOBGO4W2M220TSFKLKVFUDZ50WP4VG9", "900100953154")
Data_CLIENTES.head(5)

,task_name,task_id,task_content,date_created,status,creator,assignees,watchers
0,CLIENTE: 10_DARÍO,85ywdaqwp,,1681402517142,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...","[{'id': 3182376, 'username': 'Isaac Cabello', ...",[]
1,CLIENTE: 08_COMERCIAL,85ywdaqwd,,1681402516399,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...","[{'id': 3182376, 'username': 'Isaac Cabello', ...",[]
2,CLIENTE: 07_HAHNEMANN,85ywdaqw7,,1681402515770,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...","[{'id': 3182376, 'username': 'Isaac Cabello', ...",[]
3,CLIENTE: 06_IMAGINE,85ywdaqvy,,1681402515101,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...","[{'id': 3182376, 'username': 'Isaac Cabello', ...",[]
4,CLIENTE: 05_ROBERTO,85ywdaqvk,,1681402514508,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...","[{'id': 3182376, 'username': 'Isaac Cabello', ...",[]

In [58]:
#Normalizar "creator"
df_n = pd.DataFrame.from_dict(Data_CLIENTES)
splitted_df = pd.json_normalize(df_n['creator'])

In [59]:
splitted_df.head(5)

,id,username,color,email,profilePicture
0,3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
1,3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
2,3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
3,3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
4,3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...

In [60]:
Data_CLIENTES = Data_CLIENTES.join(splitted_df)
Data_CLIENTES = Data_CLIENTES.drop('creator', axis=1)

In [61]:
Data_CLIENTES.head(3)

,task_name,task_id,task_content,date_created,status,assignees,watchers,id,username,color,email,profilePicture
0,CLIENTE: 10_DARÍO,85ywdaqwp,,1681402517142,Open,"[{'id': 3182376, 'username': 'Isaac Cabello', ...",[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
1,CLIENTE: 08_COMERCIAL,85ywdaqwd,,1681402516399,Open,"[{'id': 3182376, 'username': 'Isaac Cabello', ...",[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
2,CLIENTE: 07_HAHNEMANN,85ywdaqw7,,1681402515770,Open,"[{'id': 3182376, 'username': 'Isaac Cabello', ...",[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...

In [62]:
Data_Proyecto_Web = get_tasks_details("pk_3041236_DXOBGO4W2M220TSFKLKVFUDZ50WP4VG9", "900100953291")

In [63]:
Data_Proyecto_SEO = get_tasks_details("pk_3041236_DXOBGO4W2M220TSFKLKVFUDZ50WP4VG9", "900100953296")

In [64]:
Data_Proyecto_RRSS = get_tasks_details("pk_3041236_DXOBGO4W2M220TSFKLKVFUDZ50WP4VG9", "900100953297")

In [65]:
Data_Proyecto_Web.head(5)

,task_name,task_id,task_content,date_created,status,creator,assignees,watchers
0,KD-WEB: CAFÉ,85ywdaw2k,,1681396253000,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...",[],[]
1,KD-WEB: ROCÍO,85ywdaw2j,,1681396048000,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...",[],[]
2,KD-WEB: DISCOTECAS,85ywdaw2f,,1681393365000,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...",[],[]
3,KD-WEB: COMERCIAL,85ywdaw29,,1681392228000,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...",[],[]
4,KD-WEB: HAHNEMANN,85ywdaw27,,1681392037000,Open,"{'id': 3182376, 'username': 'Isaac Cabello', '...",[],[]

In [66]:
Data_Proyecto_RRSS.info()
Data_Proyecto_SEO.info()
Data_Proyecto_Web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   task_name     2 non-null      object
 1   task_id       2 non-null      object
 2   task_content  2 non-null      object
 3   date_created  2 non-null      object
 4   status        2 non-null      object
 5   creator       2 non-null      object
 6   assignees     2 non-null      object
 7   watchers      2 non-null      object
dtypes: object(8)
memory usage: 256.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   task_name     1 non-null      object
 1   task_id       1 non-null      object
 2   task_content  1 non-null      object
 3   date_created  1 non-null      object
 4   status        1 non-null      object
 5   creator       1 non-null      object
 6   assignees     1 non-null      object
 7   watchers      1 non-null      object
dtypes: object(8)
memory usage: 192.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   task_name     6 non-null      object
 1   task_id       6 non-null      object
 2   task_content  6 non-null      object
 3   date_created  6 non-null      object
 4   status        6 non-null      object
 5   creator       6 non-null      object
 6   assignees     6 non-null      object
 7   watchers      6 non-null      object
dtypes: object(8)
memory usage: 512.0+ bytes

In [67]:
print(len(Data_Proyecto_RRSS))
print(len(Data_Proyecto_SEO))
print(len(Data_Proyecto_Web))

2
1
6

In [68]:
#Juntar los BD de proyectos en una:
Data_Proyectos = pd.concat([Data_Proyecto_RRSS, Data_Proyecto_SEO,Data_Proyecto_Web], axis=0)

In [69]:
print(len(Data_Proyectos))

9

In [70]:
Data_CLIENTES.info()
print(len(Data_CLIENTES))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   task_name       9 non-null      object
 1   task_id         9 non-null      object
 2   task_content    9 non-null      object
 3   date_created    9 non-null      object
 4   status          9 non-null      object
 5   assignees       9 non-null      object
 6   watchers        9 non-null      object
 7   id              9 non-null      int64
 8   username        9 non-null      object
 9   color           9 non-null      object
 10  email           9 non-null      object
 11  profilePicture  9 non-null      object
dtypes: int64(1), object(11)
memory usage: 992.0+ bytes
9

In [71]:
#Normalizar "creator" en Proyectos
df_n1 = pd.DataFrame.from_dict(Data_Proyectos)
splitted_df1 = pd.json_normalize(df_n1['creator'])


Data_Proyectos = Data_Proyectos.join(splitted_df1)
Data_Proyectos = Data_Proyectos.drop('creator', axis=1)
Data_Proyectos.head(5)

,task_name,task_id,task_content,date_created,status,assignees,watchers,id,username,color,email,profilePicture
0,KD-RRSS: LAS COSAS,85ywdaw2v,,1681393122000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
0,KD-SEO: ROBERTO,85ywdaw2q,,1681392891000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
0,KD-WEB: CAFÉ,85ywdaw2k,,1681396253000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
1,KD-RRSS: IMAGINE,85ywdaw2u,,1681392451000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...
1,KD-WEB: ROCÍO,85ywdaw2j,,1681396048000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
        <strong>TRANSFORM:</strong><br>
En la entidad Proyecto vamos a realizar algunas transformaciones: <br>
Campo PRODUCTO: Producto WEB, SEO, RRSS, etc.<br>
● 0 = KD-WEB<br>
● 1 = KD-SEO<br>
● 2 = KD-ANALITICA<br>
● 3 = KD-RRSS<br>
● 4 = KD-ECOMMERCE<br>
● 5 = KD-CRM<br>
● 6 = KD-PROC<br>
● 7 = KD-FACT<br>

<strong>Respuesta:</strong><br> 
Se realiza con la siguiente función:  
</div>

In [72]:
def add_product(df):
    list_r = []
    for row in df['task_name']:
        if "KD-WEB" in row:    list_r.append("0")
        elif "KD-SEO" in row:   list_r.append("1")
        elif "KD-ANALITICA" in row:  list_r.append("2")
        elif "KD-RRSS" in row:  list_r.append("3")
        elif "KD-ECOMMERCE" in row:  list_r.append("4")
        elif "KD-CRM" in row:  list_r.append("5")
        elif "KD-PROC" in row:  list_r.append("6")
        elif "KD-FACT" in row:  list_r.append("7")
        else: list_r.append(" ")
    df['PRODUCTO'] = list_r
    return df
 
Data_Proyectos =  add_product(Data_Proyectos)

In [73]:
Data_Proyectos.head(5)

,task_name,task_id,task_content,date_created,status,assignees,watchers,id,username,color,email,profilePicture,PRODUCTO
0,KD-RRSS: LAS COSAS,85ywdaw2v,,1681393122000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,3
0,KD-SEO: ROBERTO,85ywdaw2q,,1681392891000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,1
0,KD-WEB: CAFÉ,85ywdaw2k,,1681396253000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,0
1,KD-RRSS: IMAGINE,85ywdaw2u,,1681392451000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,3
1,KD-WEB: ROCÍO,85ywdaw2j,,1681396048000,Open,[],[],3182376,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,0

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
     <strong>TRANSFORM:</strong><br>
Los campos de tipo numérico convertirlos a tipo float/double.
<br>
<strong>Respuesta:</strong><br> 
Se realiza para la entidad Proyectos, con los campos date_created, id y PRODUCTO.   
</div>

In [74]:
Data_Proyectos['id'] = pd.to_numeric(Data_Proyectos['id'], downcast='float')

In [75]:
Data_Proyectos['PRODUCTO'] = pd.to_numeric(Data_Proyectos['PRODUCTO'], downcast='float')

In [76]:
Data_Proyectos['date_created'] = pd.to_numeric(Data_Proyectos['date_created'], downcast='float')

In [77]:
#Se aprovecha para cast a timestamp:
Data_Proyectos['date_created'] = pd.to_datetime(Data_Proyectos['date_created'], errors='coerce')
Data_Proyectos.head(5)

,task_name,task_id,task_content,date_created,status,assignees,watchers,id,username,color,email,profilePicture,PRODUCTO
0,KD-RRSS: LAS COSAS,85ywdaw2v,,1970-01-01 00:28:01.393057792,Open,[],[],3182376.0,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,3.0
0,KD-SEO: ROBERTO,85ywdaw2q,,1970-01-01 00:28:01.392926720,Open,[],[],3182376.0,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,1.0
0,KD-WEB: CAFÉ,85ywdaw2k,,1970-01-01 00:28:01.396203520,Open,[],[],3182376.0,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,0.0
1,KD-RRSS: IMAGINE,85ywdaw2u,,1970-01-01 00:28:01.392402432,Open,[],[],3182376.0,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,3.0
1,KD-WEB: ROCÍO,85ywdaw2j,,1970-01-01 00:28:01.396072448,Open,[],[],3182376.0,Isaac Cabello,#757380,isaac.cabello@orbidi.com,https://attachments.clickup.com/profilePicture...,0.0

In [78]:
#Data_CLIENTES['date_created'] = pd.to_datetime(Data_CLIENTES['date_created'])

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
        <strong>LOAD:</strong><br>
Usando el campo “ESTIMATED TIME” que hay en la entidad PROYECTO
crear una sumatoria de tiempo por tipo de PRODUCTO.
<br>
<strong>Respuesta:</strong><br> 
Se realiza con el campo "date_created", el cual fue el que encontré para poder realizar este ejercicio.   
</div>

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
        <strong>Preguntas:</strong><br>

1. Considerando que actualmente tenemos 1.000 clientes en nuestro entorno de
ClickUp de producción y que nos gustaría disponer de la información con la máxima
rapidez posible en nuestro entorno de explotación de datos. ¿Cómo plantearías la
estrategia de extracción para conseguirlo? ¿Qué retos anticipas? ¿Qué
consideraciones deberíamos tomar?
<br>
<strong>Respuesta:</strong><br> 
Es importante hacer una proyección del crecimiento de la base de datos de acuerdo al histórico, para preveer su tamaño y dar la mejor solución. Dependiendo del resultado, un datamart en snowflake puede ser una buena opción, teniendo en cuenta que es para un departamento específico (Proyectos). Si el resultado es una big data, se puede utilizar técnicas para procesar grandes cantidades de datos como Spark, MapReduce y en algunos casos HDFS.-
<br>
Un reto importante que considero es la calidad de los datos, en esta BD específica encontré datos extraños como el date_created que me dio la misma fecha.
    
</div>

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
        <strong>Preguntas:</strong><br>

2. Considerando que utilizamos un segundo sistema HubSpot dónde tenemos toda la
información de Clientes (es la verdadera base de clientes - source of truth - ). Nos
gustaría también relacionar la información de esa segunda fuente de datos con la
herramienta de gestión de clientes Clickup y sus respectivas entidades (clientes).
¿Qué estrategia consideras que deberíamos seguir? ¿Cómo resolverías el caso en
el cual en Hubspot la información de un cliente aparezca distinta que en ClickUp?
<br>
<strong>Respuesta:</strong><br> 
No lo he manejado.
    
</div>

<div style="background-color: #FAF7C9 ; border-color: #F1E985; border-left: 5px solid #F1E985; padding: 0.5em;">
        <strong>Preguntas:</strong><br>
3. ¿Cómo harías que este proceso se ejecute de forma periódica?<br>
4. ¿Qué método implementarías para detectar errores en el proceso y cómo
asegurarías su consistencia?<br>
5. ¿Cómo harías una integración entre ClickUp y HubSpot para sincronizar la
información (estados de proyectos, pagos, etc) entre ambas plataformas en tiempo
real (o con una frecuencia considerablemente alta)?<br>

<br>
<strong>Respuesta:</strong><br> 
No conozco HubSpot y Clickup apenas lo investigué para esta prueba. Sólo he manipulado archivos json, que veo es parecido.
    
</div>